* Write this tech report about path based model and call graph model about tracing

** the main theme

This path based model and call graph based model 
Also, tree vs DAG, span vs event, 

The most important insight: 
**** Cause
the call graph cannot reveal internal ordering
**** consequences:
can't programmatically abstract the causal relationship
bias in critical path analysis

** Key ideas, the most important thing I want to convey?

1. span model cant really reveal the internal ordering in the distirbuted
   systems thus cant allow programmatically abstract the critical path, or
   further analysis

** Canopy /tracing plane method:
having the impl in event based model. but still convert the visualization
method into call graph

what are the advantages and limiatations?




** Reference
*** jonathan levitte thesis 
*** tracing plane 
*** jonahtna: pivot tracing
*** jonahtna : canopy
*** google dapper
*** google short ppaer about nearest neighbour
*** argus
*** raja's tech report?
*** tiem aware provenance


** Evaluation:
*** instrunemented openstack and run experienment in the same environement but with two type of instrumentattion
*** more? (Ceph, openshift)

